services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  In2code\PowermailCond\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  In2code\PowermailCond\UserFunc\GetPowermailFields:
    public: true

  In2code\PowermailCond\UserFunc\GetPowermailFormsWithoutConditionRelation:
    public: true

  In2code\PowermailCond\Backend\Form\Element\Note:
    arguments:
      $data: []